sudo: false

language: objective-c

before_install:
    - gem install slather
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
    - brew update
    - pod install

script:
  - xcodebuild -workspace SnowplowIgluClient.xcworkspace -scheme SnowplowIgluClient -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`
  - xcodebuild test -workspace SnowplowIgluClient.xcworkspace -scheme SnowplowIgluClientTests -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`

after_success: slather
